[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/cli",
    "crates/gui-tauri/src-tauri",
    "crates/sfx-stub",
    "crates/vendor/unrar-sys",
]

[workspace.package]
version = "0.7.2"
edition = "2021"
license = "MIT"
repository = "https://github.com/GEELINX-LTD/geezipx"
documentation = "https://github.com/GEELINX-LTD/geezipx#readme"
homepage = "https://github.com/GEELINX-LTD/geezipx"
rust-version = "1.96"

[workspace.dependencies]
geezipx-core = { version = "0.7.2", path = "crates/core", default-features = false }

[patch.crates-io]
unrar_sys = { path = "crates/vendor/unrar-sys" }