[workspace]
resolver = "2"
members = [
    "crates/core",
    "crates/cli",
]

[workspace.package]
version = "0.3.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/GEELINX-LTD/geezipx"
documentation = "https://github.com/GEELINX-LTD/geezipx#readme"
homepage = "https://github.com/GEELINX-LTD/geezipx"
rust-version = "1.96"

[workspace.dependencies]
geezipx-core = { version = "0.3.0", path = "crates/core", default-features = false }
